export const CITIES = [
  { city: "Taubaté", state: "SP", total: 38 },
  { city: "São Luiz do Paraitinga", state: "SP", total: 18 },
  { city: "Pindamonhangaba", state: "SP", total: 10 },
  { city: "Jambeiro", state: "SP", total: 6 },
  { city: "Gonçalves", state: "MG", total: 1 },
  { city: "Bofete", state: "SP", total: 1 },
  { city: "São Miguel Arcanjo", state: "SP", total: 1 },
  { city: "São José dos Campos", state: "SP", total: 19 },
  { city: "Piedade", state: "SP", total: 1 },
  { city: "São Roque", state: "SP", total: 2 },
  { city: "Delfim Moreira", state: "MG", total: 1 },
  { city: "Itapetininga", state: "SP", total: 2 },
  { city: "Caçapava", state: "SP", total: 14 },
  { city: "Guararema", state: "SP", total: 1 },
  { city: "Cunha", state: "SP", total: 8 },
  { city: "Natividade da Serra", state: "SP", total: 9 },
  { city: "Cocos", state: "BA", total: 1 },
  { city: "Jacareí", state: "SP", total: 5 },
  { city: "Ribeirão Preto", state: "SP", total: 2 },
  { city: "Paraibuna", state: "SP", total: 6 },
  { city: "Tremembé", state: "SP", total: 5 },
  { city: "Martins Soares", state: "MG", total: 1 },
  { city: "Santo Antônio do Pinhal", state: "SP", total: 1 },
  { city: "Lagoinha", state: "SP", total: 1 },
  { city: "Lorena", state: "SP", total: 1 },
  { city: "Guaratinguetá", state: "SP", total: 3 },
  { city: "São José do Barreiro", state: "SP", total: 1 },
  { city: "Goiânia", state: "GO", total: 1 },
  { city: "Cachoeira Paulista", state: "SP", total: 1 },
  { city: "Franca", state: "SP", total: 1 },
  { city: "Ibiúna", state: "SP", total: 1 },
  { city: "Botucatu", state: "SP", total: 1 },
  { city: "Redenção da Serra", state: "SP", total: 1 },
  { city: "Santa Branca", state: "SP", total: 1 },
  { city: "Mairinque", state: "SP", total: 1 },
  { city: "Franco da Rocha", state: "SP", total: 1 },
  { city: "Sapucaí-Mirim", state: "MG", total: 1 },
  { city: "Cruzeiro", state: "SP", total: 1 },
];
